# Generated by Django 5.0 on 2024-01-02 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='VotingGame',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_code', models.CharField(max_length=30, unique=True)),
                ('game_name', models.CharField(max_length=50)),
                ('game_link', models.CharField(max_length=100)),
                ('no_of_votes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField()),
                ('comments', models.CharField(max_length=500)),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.choices')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.users')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.votinggame')),
            ],
        ),
        migrations.CreateModel(
            name='GameUsers',
            fields=[
                ('game_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.users')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.votinggame')),
            ],
        ),
        migrations.AddField(
            model_name='choices',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.votinggame'),
        ),
    ]
