# Generated by Django 4.2.9 on 2024-02-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_alter_choices_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='Rawal@123', max_length=100),
            preserve_default=False,
        ),
    ]
