# Generated by Django 4.2.9 on 2024-02-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_users_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='id',
        ),
    ]
