# Generated by Django 4.2.9 on 2024-02-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='user',
        ),
    ]
